export const routePaths = {
  home: "/",
  search: "/search",
  userGenres: "/genres",
  userGenreDetail: (genreId = ":id") => `/genres/${genreId}`,
  dailyTopTracks: "/charts/daily-top-tracks",
  monthlyTopTracks: "/charts/monthly-top-tracks",
  albumDetail: (albumId = ":id") => `/albums/${albumId}`,
  playlistDetail: (playlistId = ":id") => `/playlists/${playlistId}`,
  lyrics: "/lyrics",
  trackDetail: (trackId = ":id") => `/tracks/${trackId}`,
  artistTrackDetail: (trackId = ":id") => `/artist/music/${trackId}`,
  artistTrackEdit: (trackId = ":id") => `/artist/music/${trackId}/edit`,
  artistLyrics: "/artist/lyrics",
  artistAlbums: "/artist/albums",
  artistAlbumDetail: (albumId = ":id") => `/artist/albums/${albumId}`,
  artistCreateAlbum: "/artist/albums/create",
  artistEditAlbum: (albumId = ":id") => `/artist/albums/${albumId}/edit`,
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  premium: "/premium",
  premiumPaymentSuccess: "/premium/payment/success",
  premiumPaymentFailed: "/premium/payment/failed",
  artistBrowseProfile: (artistId = ":id") => `/artists/${artistId}`,
  legacyArtistProfile: "/artist-profile",
  userProfile: "/profile",
  userRecentListeningActivity: "/user/recent-listening-activity",
  notifications: "/notifications",
  artistRegistrationRequest: "/artist-registration-request",
  artistRegistrationRequestsList: "/my-artist-registration-requests",
  artistRegistrationRequestsDetail: (requestId = ":id") => `/my-artist-registration-requests/${requestId}`,
  artistRoot: "/artist",
  artistMusic: "/artist/music",
  artistCreateTrack: "/artist/music/create",
  artistReleases: "/artist/releases",
  artistCreateReleaseSchedule: "/artist/releases/create",
  artistEditReleaseSchedule: (scheduleId = ":id") => `/artist/releases/${scheduleId}/edit`,
  artistReleaseScheduleDetail: (scheduleId = ":id") => `/artist/releases/${scheduleId}`,
  artistAnalytics: "/artist/analytics",
  artistNotifications: "/artist/notifications",
  artistFollowers: "/artist/followers",
  artistNotificationDetail: (notificationId = ":id") => `/artist/notifications/${notificationId}`,
  artistRoyalties: "/artist/royalties",
  artistBalanceManagement: "/artist/royalties/balance",
  artistRevenueHistory: "/artist/royalties/history",
  artistRevenuePeriodDetail: (periodId = ":id") => `/artist/royalties/history/${periodId}`,
  artistWithdrawalRequests: "/artist/withdrawal-requests",
  artistSettings: "/artist/settings",
  artistProfile: "/artist/profile",
  artistProfileEdit: "/artist/profile/edit",
  userPlaylist: "/user/playlist",
  userPaymentHistory: "/payment-history",
  userPaymentReceipt: "/payment-history/:paymentId/receipt",
  userPlaylistDetail: (playlistId = ":id") => `/user/playlist/${playlistId}`,
  userFavoriteTracks: "/user/favorite-tracks",
  userCreateReport: "/user/reports/create",
  userReportList: "/user/reports",
  userReportDetail: (reportId = ":id") => `/user/reports/${reportId}`,

  libraryFollowedArtists: "/library/followed-artists",
  libraryFollowedAlbums: "/library/followed-albums",
};

