export const routePaths = {
  home: "/",
  dailyTopTracks: "/charts/daily-top-tracks",
  monthlyTopTracks: "/charts/monthly-top-tracks",
  albumDetail: (albumId = ":id") => `/albums/${albumId}`,
  playlistDetail: (playlistId = ":id") => `/playlists/${playlistId}`,
  lyrics: "/lyrics",
  trackDetail: (trackId = ":id") => `/tracks/${trackId}`,
  artistTrackDetail: (trackId = ":id") => `/artist/music/${trackId}`,
  artistTrackEdit: (trackId = ":id") => `/artist/music/${trackId}/edit`,
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  artistBrowseProfile: (artistId = ":id") => `/artists/${artistId}`,
  legacyArtistProfile: "/artist-profile",
  artistRoot: "/artist",
  artistMusic: "/artist/music",
  artistCreateTrack: "/artist/music/create",
  artistReleases: "/artist/releases",
  artistAnalytics: "/artist/analytics",
  artistFans: "/artist/fans",
  artistRoyalties: "/artist/royalties",
  artistSettings: "/artist/settings",
  artistProfile: "/artist/profile",
  artistProfileEdit: "/artist/profile/edit",
};
