export const routePaths = {
  home: "/",
  albumDetail: (albumId = ":id") => `/albums/${albumId}`,
  lyrics: "/lyrics",
  trackDetail: (trackId = ":id") => `/tracks/${trackId}`,
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  artistBrowseProfile: (artistId = ":id") => `/artists/${artistId}`,
  legacyArtistProfile: "/artist-profile",
  artistRoot: "/artist",
  artistMusic: "/artist/music",
  artistReleases: "/artist/releases",
  artistAnalytics: "/artist/analytics",
  artistFans: "/artist/fans",
  artistRoyalties: "/artist/royalties",
  artistSettings: "/artist/settings",
  artistProfile: "/artist/profile",
  artistProfileEdit: "/artist/profile/edit",
};
