export const routePaths = {
  home: "/",
  login: "/login",
  systemTracks: "/system-tracks",
  podcasts: "/podcasts",
  advertisements: "/advertisements",
  advertisementNew: "/advertisements/new",
  advertisementDetail: (id = ":id") => `/advertisements/${id}`,
  advertisementEdit: (id = ":id") => `/advertisements/${id}/edit`,
  podcastDetail: (podcastId = ":id") => `/podcasts/${podcastId}`,
  systemAlbums: "/system-albums",
  trackModeration: "/system-tracks/moderation",
  trackAppeals: "/track-appeals",
  trackAppealDetail: (appealId = ":appealId") => `/track-appeals/${appealId}`,
  artistRequests: "/artist-requests",
  artistRequestDetail: (requestId = ":requestId") => `/artist-requests/${requestId}`,
  trackDetail: (trackId = ":id") => `/system-tracks/${trackId}`,
  albumDetail: (albumId = ":id") => `/system-albums/${albumId}`,
  systemPlaylists: "/system-playlists",
  genres: "/genres",
  genreNew: "/genres/new",
  systemArtists: "/system-artists",
  artistDetail: (artistId = ":id") => `/system-artists/${artistId}`,
  genreEdit: (genreId = ":genreId") => `/genres/${genreId}/edit`,
  users: "/users",
  adminList: "/users/admins",
  userDetail: (userId = ":userId") => `/users/${userId}`,
  systemPlaylistNew: "/system-playlists/new",
  systemPlaylistDetail: (playlistId = ":playlistId") =>
    `/system-playlists/${playlistId}`,
  systemPlaylistEdit: (playlistId = ":playlistId") =>
    `/system-playlists/${playlistId}/edit`,
  notifications: "/notifications",
  createNotification: "/notifications/new",
  notificationDetail: (notificationId = ":id") => `/notifications/${notificationId}`,
  notificationEdit: (notificationId = ":id") => `/notifications/${notificationId}/edit`,
  revenue: "/revenue",
  revenueHistory: "/revenue/history",
  withdrawals: "/withdrawals",
  withdrawalRequestDetail: (withdrawalRequestId = ":id") =>
    `/withdrawal-requests/${withdrawalRequestId}`,
  revenuePeriodDetail: (periodId = ":periodId") => `/revenue/history/${periodId}`,
  revenueSharingHistory: "/revenue-sharing",
  revenueSharingDetail: (periodId = ":periodId") =>
    `/revenue-sharing/${periodId}`,
  reports: "/reports",
  artistViolations: "/artist-violations",
  createArtistViolation: "/artist-violations/new",
  artistViolationDetail: (targetType = ":targetType", targetId = ":targetId") =>
    `/artist-violations/detail/${targetType}/${targetId}`,
  reportDetail: (reportId = ":reportId") => `/reports/${reportId}`,
  groupedReportDetail: (targetType = ":targetType", targetId = ":targetId") =>
    `/reports/grouped/${targetType}/${targetId}`,
  subscriptions: "/subscriptions",
  subscriptionDetail: (planId = ":planId") => `/subscriptions/${planId}`,
  subscriptionEdit: (planId = ":planId") => `/subscriptions/${planId}/edit`,
  subscriptionNew: "/subscriptions/new",
  transactions: "/transactions",
  transactionDetail: (transactionId = ":id") => `/transactions/${transactionId}`,
};
