export const routePaths = {
  home: "/",
  login: "/login",
  systemTracks: "/system-tracks",
  trackModeration: "/system-tracks/moderation",
  artistRequests: "/artist-requests",
  artistRequestDetail: (requestId = ":requestId") => `/artist-requests/${requestId}`,
  trackDetail: (trackId = ":id") => `/system-tracks/${trackId}`,
  systemPlaylists: "/system-playlists",
  genres: "/genres",
  genreNew: "/genres/new",
  systemArtists: "/system-artists",
  artistDetail: (artistId = ":id") => `/system-artists/${artistId}`,
  genreEdit: (genreId = ":genreId") => `/genres/${genreId}/edit`,
  users: "/users",
  adminList: "/users/admins",
  userDetail: (userId = ":userId") => `/users/${userId}`,
  systemPlaylistNew: "/system-playlists/new",
  systemPlaylistDetail: (playlistId = ":playlistId") =>
    `/system-playlists/${playlistId}`,
  systemPlaylistEdit: (playlistId = ":playlistId") =>
    `/system-playlists/${playlistId}/edit`,
  revenue: "/revenue",
  revenueHistory: "/revenue/history",
  revenuePeriodDetail: (year = ":year", month = ":month") =>
    `/revenue/history/${year}/${month}`,
  reports: "/reports",
  reportDetail: (reportId = ":reportId") => `/reports/${reportId}`,
  subscriptions: "/subscriptions",
  subscriptionDetail: (planId = ":planId") => `/subscriptions/${planId}`,
  subscriptionEdit: (planId = ":planId") => `/subscriptions/${planId}/edit`,
  subscriptionNew: "/subscriptions/new",
};
